/* hwhb_32.c - hwhb_32 font for UCGUI font driver */ 
/********************************************************************************************************
*                                            UCGUI
*                                       http://www.ucgui.com
*
*                             (c) Copyright 2005-2006, UCGUI专业论坛, 学习交流UCGUI
*
*                               	ucgui@16.com 2005.07.31
*                                           作者: ucgui
*********************************************************************************************************
*/

#include "GUI.H" 
#ifndef GUI_FLASH 
	#define GUI_FLASH 
#endif 
extern GUI_FLASH const GUI_FONT GUI_FontHZ_hwhb_32;

GUI_FLASH  const unsigned char acFontHZhwhb_32_0032[99] = {	/* 2 0x3200*/
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
______XX,XXXX____,________,
____XXXX,XXXXXX__,________,
___XXXXX,XXXXXXX_,________,
___XXXXX,XXXXXXX_,________,
__XXXXXX,XXXXXXXX,________,
__XXXXX_,__XXXXXX,________,
__XXXXX_,___XXXXX,________,
__XXXXX_,___XXXXX,________,
__XXXXX_,__XXXXXX,________,
___XXX__,__XXXXX_,________,
___XXX__,_XXXXXX_,________,
____X___,_XXXXX__,________,
________,XXXXXX__,________,
_______X,XXXXX___,________,
_______X,XXXXX___,________,
______XX,XXXXXXXX,________,
______XX,XXXXXXXX,________,
_____XXX,XXXXXXXX,________,
_____XXX,XXXXXXXX,________,
____XXXX,XXXXXXXX,________,
____XXXX,XXXXXXXX,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_0033[99] = {	/* 3 0x3300*/
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
____XXXX,XXXXXX__,________,
____XXXX,XXXXX___,________,
____XXXX,XXXXX___,________,
____XXXX,XXXXX___,________,
____XXXX,XXXX____,________,
______XX,XXXX____,________,
______XX,XXX_____,________,
______XX,XXX_____,________,
_____XXX,XXX_____,________,
_____XXX,XXXX____,________,
________,XXXXX___,________,
________,XXXXXX__,________,
________,_XXXXX__,________,
________,_XXXXX__,________,
________,XXXXXX__,________,
________,XXXXXX__,________,
____XXXX,XXXXXX__,________,
____XXXX,XXXXX___,________,
____XXXX,XXXXX___,________,
____XXXX,XXXX____,________,
____XXXX,XX______,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_004d[132] = {	/* M 0x4d00*/
________,________,________,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
_____XXX,XXX____X,XXXXX___,________,
____XXXX,XXXX__XX,XXXXXXX_,________,
___XXXXX,XXXXXXXX,XXXXXXX_,________,
__XXXXXX,XXXXXXXX,XXXXXXXX,________,
__XXXXXX,XXXXXXXX,XXXXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
__XXXXXX,__XXXXXX,__XXXXXX,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_0053[66] = {	/* S 0x5300*/
________,________,
________,________,
________,________,
________,________,
________,________,
______XX,XXXX____,
_____XXX,XXXX____,
____XXXX,XXXX____,
___XXXXX,XXXX____,
___XXXXX,XXXX____,
___XXXXX,XX______,
___XXXXX,X_______,
___XXXXX,X_______,
___XXXXX,X_______,
___XXXXX,XX______,
____XXXX,XX______,
____XXXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_XXXXXXX,XXX_____,
_XXXXXXX,XXX_____,
_XXXXXXX,XX______,
_XXXXXXX,X_______,
_XXXXXXX,________,
__XXXXX_,________,
________,________,
________,________,
________,________,
________,________,
________,________,
________,________,
________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_0054[66] = {	/* T 0x5400*/
________,________,
________,________,
________,________,
________,________,
________,________,
_XXXXXXX,XXXXXXXX,
_XXXXXXX,XXXXXXXX,
_XXXXXXX,XXXXXXXX,
_XXXXXXX,XXXXXXXX,
_XXXXXXX,XXXXXXXX,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
_____XXX,XXX_____,
________,________,
________,________,
________,________,
________,________,
________,________,
________,________,
________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_b0e5[132] = {	/* 板 0xb0e5*/
________,________,________,________,
________,________,________,________,
______XX,XXX_____,_______X,XXXXXX__,
_____XXX,XXX____X,XXXXXXXX,XXXXXXX_,
_____XXX,XXX___XX,XXXXXXXX,XXXXXXX_,
_____XXX,XXX___XX,XXXXXXXX,XXXXXXX_,
_____XXX,XXX_____,XXXXXXXX,XXXXXX__,
___XXXXX,XXXXX___,XXXXXXXX,XXXX____,
__XXXXXX,XXXXXX__,XXXX____,________,
__XXXXXX,XXXXXX__,XXX_____,________,
__XXXXXX,XXXXXX__,XXXXXXXX,XXX_____,
__XXXXXX,XXXXXX__,XXXXXXXX,XXXXX___,
_____XXX,________,XXXXXXXX,XXXXXX__,
_____XX_,_______X,XXXXXXXX,XXXXXX__,
_____XX_,_XXX___X,XXX____X,XXXXXX__,
____XXX_,_XXXX__X,X_______,_XXXXX__,
____XXX_,_XXXX___,X__XXX__,_XXXXX__,
___XXXX_,_XXXXX__,X__XXXX_,_XXXX___,
___XXXXX,__XXXX__,X__XXXXX,XXXXX___,
__XXXXXX,__XXX___,X__XXXXX,XXXXX___,
__XXXXXX,X_______,X___XXXX,XXXXX___,
__XXXXXX,XX____XX,XX__XXXX,XXXX____,
__XXXXXX,XXX__XXX,XX___XXX,XXXX____,
____XXXX,XXX__XXX,X___XXXX,XXXX____,
_____XXX,XX___XXX,___XXXXX,XXXXX___,
_____XXX,XX__XXX_,__XXXXXX,XXXXXX__,
_____XXX,XX__XXX_,_XXXXXXX,XXXXXXX_,
_____XXX,XX__XXX_,_XXXXXXX,XXXXXXX_,
_____XXX,XX__XXX_,_XXXXXX_,_XXXXXX_,
_____XXX,XX__XXX_,_XXXXX__,__XXXX__,
______XX,XX___XX_,__XXX___,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_b0e6[132] = {	/* 版 0xb0e6*/
________,________,________,________,
________,________,________,________,
_____XX_,____X___,________,____XX__,
____XXXX,___XXX__,__XXXXXX,XXXXXXX_,
____XXXX,__XXXXX_,_XXXXXXX,XXXXXXX_,
____XXXX,__XXXXX_,_XXXXXXX,XXXXXXX_,
____XXXX,__XXXXX_,_XXXXXXX,XXXXXXX_,
____XXXX,__XXXXX_,_XXXXXXX,XXXXXX__,
____XXXX,__XXXXX_,__XXXX__,________,
____XXXX,__XXXXX_,__XXXX__,________,
____XXXX,XXXXXXXX,__XXXX__,________,
____XXXX,XXXXXXXX,X__XXXXX,XXXXX___,
____XXXX,XXXXXXXX,X__XXXXX,XXXXXX__,
____XXXX,XXXXXXXX,__XXX___,XXXXXX__,
____XXXX,X_______,__X_____,_XXXXX__,
____XXXX,X_______,______X_,__XXXX__,
____XXXX,X_______,_X__XXXX,__XXXX__,
____XXXX,XXXXXX__,_X__XXXX,XXXXXX__,
____XXXX,XXXXXX__,XX__XXXX,XXXXX___,
____XXXX,XXXXXX__,XX__XXXX,XXXXX___,
____XXXX,XXXXXX__,XX___XXX,XXXX____,
____XXXX,XXXXXX__,XXX__XXX,XXXX____,
____XXXX,__XXX__X,XXX__XXX,XXXX____,
___XXXXX,__XXX__X,XX___XXX,XXXX____,
___XXXXX,__XX___X,X___XXXX,XXXXX___,
___XXXXX,__XX__XX,___XXXXX,XXXXXX__,
__XXXXXX,__XX__X_,__XXXXXX,XXXXXXX_,
__XXXXX_,__XX__X_,_XXXXXXX,_XXXXXX_,
__XXXXX_,__XX__X_,__XXXXX_,__XXXXX_,
___XXX__,___X___X,__XXXX__,___XXX__,
________,___XX___,________,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_b6b7[132] = {	/* 斗 0xb6b7*/
________,________,________,________,
________,________,________,________,
________,________,________,________,
____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
______XX,XXXXXXXX,XXXXXXXX,XX______,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
________,XXXXXX__,___XXXXX,________,
________,XXXXX___,___XXXXX,________,
_______X,XXXXX___,___XXXXX,________,
_______X,XXXXX___,___XXXXX,________,
_____XXX,XXXX____,___XXXXX,________,
____XXXX,XXXX____,___XXXXX,________,
___XXXXX,XXX_____,___XXXXX,________,
__XXXXXX,XX______,___XXXXX,________,
__XXXXXX,X_______,___XXXXX,________,
__XXXXXX,________,___XXXXX,________,
___XXXX_,________,___XXXX_,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_b7a2[132] = {	/* 发 0xb7a2*/
________,________,________,________,
________,________,________,________,
________,______XX,XX____XX,X_______,
________,_____XXX,XXX__XXX,XX______,
_____XXX,X____XXX,XXX__XXX,XX______,
_____XXX,XX___XXX,XX____XX,XXX_____,
_____XXX,XX___XXX,XX____XX,XXX_____,
_____XXX,XX__XXXX,XX_____X,XX______,
_____XXX,XXXXXXXX,XXXXX___,____XXX_,
_____XXX,XXXXXXXX,XXXXXX__,___XXXX_,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
________,XXXXXXXX,XXXXXXXX,XXXXX___,
________,__XXXXXX,________,________,
________,__XXXXXX,XXXXXXXX,XXXX____,
________,__XXXX__,_XXXXXXX,XXXXX___,
________,_XXX____,__XXXXXX,XXXXX___,
________,_XXX___X,___XXXXX,XXXXX___,
________,XXX__XXX,X______X,XXXXX___,
________,XXX__XXX,XX_____X,XXXX____,
_______X,XXX__XXX,XXX___XX,XXXX____,
______XX,XXX___XX,XXXXXXXX,XXX_____,
______XX,XXXX___X,XXXXXXXX,XX______,
_____XXX,XXXX____,XXXXXXXX,X_______,
____XXXX,XXX_____,XXXXXXXX,X_______,
____XXXX,XX_____X,XXXXXXXX,XXXX____,
___XXXXX,X____XXX,XXXXXXXX,XXXXXX__,
___XXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,
___XXXXX,__XXXXXX,XXX___XX,XXXXXXXX,
___XXXXX,__XXXXXX,X_______,XXXXXXX_,
____XXX_,___XXXX_,________,__XXXXX_,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_b7dc[132] = {	/* 奋 0xb7dc*/
________,________,________,________,
________,________,________,________,
________,______XX,XX____XX,X_______,
________,_____XXX,XXX__XXX,XX______,
_____XXX,X____XXX,XXX__XXX,XX______,
_____XXX,XX___XXX,XX____XX,XXX_____,
_____XXX,XX___XXX,XX____XX,XXX_____,
_____XXX,XX__XXXX,XX_____X,XX______,
_____XXX,XXXXXXXX,XXXXX___,____XXX_,
_____XXX,XXXXXXXX,XXXXXX__,___XXXX_,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
________,XXXXXXXX,XXXXXXXX,XXXXX___,
________,__XXXXXX,________,________,
________,__XXXXXX,XXXXXXXX,XXXX____,
________,__XXXX__,_XXXXXXX,XXXXX___,
________,_XXX____,__XXXXXX,XXXXX___,
________,_XXX___X,___XXXXX,XXXXX___,
________,XXX__XXX,X______X,XXXXX___,
________,XXX__XXX,XX_____X,XXXX____,
_______X,XXX__XXX,XXX___XX,XXXX____,
______XX,XXX___XX,XXXXXXXX,XXX_____,
______XX,XXXX___X,XXXXXXXX,XX______,
_____XXX,XXXX____,XXXXXXXX,X_______,
____XXXX,XXX_____,XXXXXXXX,X_______,
____XXXX,XX_____X,XXXXXXXX,XXXX____,
___XXXXX,X____XXX,XXXXXXXX,XXXXXX__,
___XXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,
___XXXXX,__XXXXXX,XXX___XX,XXXXXXXX,
___XXXXX,__XXXXXX,X_______,XXXXXXX_,
____XXX_,___XXXX_,________,__XXXXX_,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_bebf[132] = {	/* 究 0xbebf*/
________,________,________,________,
________,________,________,________,
________,_____XXX,XXX_____,________,
________,____XXXX,XXXX____,________,
____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,_XXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,__XXXXX_,__XXXXX_,__XXXX__,
__XXXX__,_XXXXXX_,__XXXXXX,___XXX__,
__XX____,_XXXXXX_,___XXXXX,X___XX__,
______XX,XX______,____XXXX,XX___X__,
_____XXX,X_______,_____XXX,XXX_____,
_____XXX,___XXXX_,______XX,XXX_____,
_____XXX,__XXXXXX,_______X,XXX_____,
______X_,__XXXXXX,________,XX______,
________,__XXXXXX,XXXXXX__,________,
____X___,_XXXXXXX,XXXXXXX_,________,
____XXXX,XXXXXXXX,XXXXXXXX,X_______,
____XXXX,XXXXXXXX,XXXXXXXX,X_______,
______XX,XXXXXXXX,XXXXXXXX,X_______,
________,XXXXXXXX,___XXXXX,________,
________,XXXXXXX_,___XXXXX,________,
_______X,XXXXXXX_,___XXXX_,__XXXX__,
_____XXX,XXXXXX__,___XXXXX,XXXXXX__,
___XXXXX,XXXXX___,___XXXXX,XXXXXX__,
__XXXXXX,XXXXX___,___XXXXX,XXXXXX__,
__XXXXXX,XXX_____,___XXXXX,XXXXXX__,
__XXXXXX,X_______,___XXXXX,XXXXX___,
___XXXX_,________,____XXXX,XXXX____,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_bfaa[132] = {	/* 开 0xbfaa*/
________,________,________,________,
________,________,________,________,
________,________,________,________,
____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
______XX,XXXXXXXX,XXXXXXXX,XX______,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
________,_XXXXX__,___XXXXX,________,
____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
________,XXXXXX__,___XXXXX,________,
________,XXXXX___,___XXXXX,________,
_______X,XXXXX___,___XXXXX,________,
_______X,XXXXX___,___XXXXX,________,
_____XXX,XXXX____,___XXXXX,________,
____XXXX,XXXX____,___XXXXX,________,
___XXXXX,XXX_____,___XXXXX,________,
__XXXXXX,XX______,___XXXXX,________,
__XXXXXX,X_______,___XXXXX,________,
__XXXXXX,________,___XXXXX,________,
___XXXX_,________,___XXXX_,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_c6bd[132] = {	/* 平 0xc6bd*/
________,________,________,________,
________,________,________,________,
____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
__XXXX__,_XXXXXXX,XXXXXXXX,XXXXXX__,
___X____,_____XXX,XXX_____,____XX__,
_______X,_____XXX,XXX_____,X_______,
_____XXX,X____XXX,XXX____X,XXX_____,
_____XXX,XX___XXX,XXX____X,XXXX____,
_____XXX,XX___XXX,XXX___XX,XXX_____,
_____XXX,XXX__XXX,XXX__XXX,XXX_____,
______XX,XXXX__XX,XX___XXX,XXX_____,
______XX,XXXX__XX,XX__XXXX,XX______,
_______X,XXXX___X,XX__XXXX,XX______,
_______X,XXXXX__X,XX__XXXX,X_______,
__XXXX__,XXXX___X,XX___XXX,___XXX__,
__XXXX__,_X____XX,XX______,__XXXX__,
_XXXXXX_,_____XXX,XXXX____,_XXXXXX_,
_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,_____XXX,XXX_____,________,
________,______XX,XX______,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_cca8[132] = {	/* 台 0xcca8*/
________,________,________,________,
________,________,________,________,
________,___XXXX_,________,________,
________,__XXXXXX,________,________,
________,_XXXXXXX,______XX,XX______,
________,_XXXXXXX,_____XXX,XX______,
________,XXXXXXX_,_____XXX,XXX_____,
_______X,XXXXXX__,_____XXX,XXXX____,
______XX,XXXXXX__,______XX,XXXXX___,
______XX,XXXXX___,_______X,XXXXX___,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
________,________,________,________,
________,XXXXXXXX,XXXXXXXX,XX______,
______XX,XXXXXXXX,XXXXXXXX,XXXXX___,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
_____XXX,XXX_____,_______X,XXXXX___,
_____XXX,XXX_____,_______X,XXXXX___,
_____XXX,XXX_____,_______X,XXXXX___,
_____XXX,XXX_____,_______X,XXXXX___,
_____XXX,XXX_____,_______X,XXXXX___,
_____XXX,XXXX____,_______X,XXXXX___,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
_____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
______XX,XXXXXXXX,XXXXXXXX,XXXXX___,
_______X,XXXXXXXX,XXXXXXXX,XXXX____,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_d1d0[132] = {	/* 研 0xd1d0*/
________,________,________,________,
________,________,________,________,
________,_______X,XXXXXXXX,XXXXX___,
__XXXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXX__X,XXXXXXXX,XXXXX___,
_____XXX,XX______,XXXXX__X,XXXX____,
_____XXX,XX______,XXXXX__X,XXXX____,
_____XXX,XX______,XXXXX__X,XXXX____,
____XXXX,X_______,XXXXX__X,XXXX____,
____XXXX,XXXX____,XXXXX__X,XXXX____,
___XXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
___XXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXX_XXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,__XX__XX,XXXXXXXX,XXXXXX__,
__XXXXXX,__XX____,XXXXXX_X,XXXX____,
__XXXXXX,__XXX___,XXXXX__X,XXXX____,
____XXXX,__XXXX__,XXXXX__X,XXXX____,
____XXXX,__XXXX__,XXXXX__X,XXXX____,
____XXXX,__XXXX__,XXXXX__X,XXXX____,
____XXXX,__XXXX_X,XXXXX__X,XXXX____,
____XXXX,XXXXX__X,XXXX___X,XXXX____,
____XXXX,XXXXX__X,XXXX___X,XXXX____,
____XXXX,XXXX___X,XXXX___X,XXXX____,
____XXXX,XXXX__XX,XXXX___X,XXXX____,
______XX,XXXX__XX,XXX____X,XXXX____,
________,______XX,XXX_____,XXXX____,
________,_______X,XX______,XXX_____,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_d5df[132] = {	/* 者 0xd5df*/
________,________,________,________,
________,________,________,________,
________,_____XXX,X_______,________,
________,____XXXX,XX______,__X_____,
________,____XXXX,XX______,_XXX____,
____XXXX,XXXXXXXX,XXXXXXX_,_XXXX___,
____XXXX,XXXXXXXX,XXXXXXXX,_XXXX___,
____XXXX,XXXXXXXX,XXXXXXX_,_XXXX___,
____XXXX,XXXXXXXX,XXXXXXX_,_XXX____,
_____XXX,XXXXXXXX,XX______,_XX_____,
________,____XXXX,XX______,XXX_____,
____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
________,__XXXXXX,X_______,________,
________,_XXXXXXX,XXXXXXXX,X_______,
______XX,XXXXXXXX,XXXXXXXX,XXX_____,
___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
__XXXXXX,XXXX____,_______X,XXX_____,
__XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
_______X,XXXXXXXX,XXXXXXXX,XXX_____,
_______X,XXXXXXXX,XXXXXXXX,XXX_____,
_______X,XXXX____,_______X,XXX_____,
_______X,XXXXXXXX,XXXXXXXX,XXX_____,
_______X,XXXXXXXX,XXXXXXXX,XXX_____,
________,XXXXXXXX,XXXXXXXX,XXX_____,
________,_XXXXXXX,XXXXXXXX,X_______,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH  const unsigned char acFontHZhwhb_32_d7f7[132] = {	/* 作 0xd7f7*/
________,________,________,________,
________,________,________,________,
________,__XXXX__,_XXXX___,________,
________,_XXXXX__,XXXXXX__,________,
________,_XXXXX__,XXXXXX__,________,
________,XXXXX__X,XXXXXX__,________,
________,XXXXX__X,XXXXXXXX,XXXXXXX_,
_______X,XXXXX__X,XXXXXXXX,XXXXXXXX,
_______X,XXXX___X,XXXXXXXX,XXXXXXXX,
_______X,XXXX__XX,XXXXXXXX,XXXXXXXX,
______XX,XXX___XX,XXXXXXXX,XXXXXXXX,
_____XXX,XXX__XXX,XXX_XXX_,________,
_____XXX,XXX__XXX,XX__XXX_,________,
____XXXX,XX__XXXX,XX__XXXX,XXXXXXX_,
___XXXXX,XX__XXXX,X___XXXX,XXXXXXXX,
___XXXXX,XX__XXXX,X__XXXXX,XXXXXXXX,
___XXXXX,XXX___XX,___XXXXX,XXXXXXXX,
___XXXXX,XXX_____,__XXXXXX,XXXXXXX_,
____XXXX,XXXXX___,__XXXXX_,________,
_______X,XXXXX___,__XXXXX_,________,
_______X,XXXXX___,__XXXXXX,XXXXXXXX,
_______X,XXXXX___,__XXXXXX,XXXXXXXX,
_______X,XXXXX___,__XXXXXX,XXXXXXXX,
_______X,XXXXX___,__XXXXXX,XXXXXXXX,
_______X,XXXXX___,__XXXXXX,XXXXXXX_,
_______X,XXXXX___,__XXXXX_,________,
_______X,XXXXX___,__XXXXX_,________,
_______X,XXXXX___,__XXXXX_,________,
_______X,XXXXX___,__XXXXX_,________,
_______X,XXXX____,__XXXXX_,________,
________,XXXX____,___XXX__,________,
________,________,________,________,
________,________,________,________,
};

GUI_FLASH const GUI_CHARINFO GUI_FontHZhwhb_32_CharInfo[7710] = {
{ 18, 18, 3, (void GUI_FLASH *)&acFontHZhwhb_32_0032},/* 2 0 */
{ 18, 18, 3, (void GUI_FLASH *)&acFontHZhwhb_32_0033},/* 3 1 */
{ 26, 26, 4, (void GUI_FLASH *)&acFontHZhwhb_32_004d},/* M 2 */
{ 13, 13, 2, (void GUI_FLASH *)&acFontHZhwhb_32_0053},/* S 3 */
{ 16, 16, 2, (void GUI_FLASH *)&acFontHZhwhb_32_0054},/* T 4 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_b0e5},/* 板 96 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_b0e6},/* 版 97 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_b6b7},/* 斗 98 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_b7a2},/* 发 99 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_b7dc},/* 奋 100 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_bebf},/* 究 101 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_bfaa},/* 开 102 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_c6bd},/* 平 103 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_cca8},/* 台 104 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_d1d0},/* 研 105 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_d5df},/* 者 106 */
{ 32, 32, 4, (void GUI_FLASH *)&acFontHZhwhb_32_d7f7},/* 作 107 */
};

/*作--作*/

GUI_FLASH const GUI_FONT_PROP GUI_FontHZhwhb_32_Propd7f7= {
      0xd7f7,
      0xd7f7,
      &GUI_FontHZhwhb_32_CharInfo[16],
      (void *)0 
};
/*者--者*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propd5df= {
      0xd5df,
      0xd5df,
      &GUI_FontHZhwhb_32_CharInfo[15],
      (void *)&GUI_FontHZhwhb_32_Propd7f7 
};
/*研--研*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propd1d0= {
      0xd1d0,
      0xd1d0,
      &GUI_FontHZhwhb_32_CharInfo[14],
      (void *)&GUI_FontHZhwhb_32_Propd5df 
};
/*台--台*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propcca8= {
      0xcca8,
      0xcca8,
      &GUI_FontHZhwhb_32_CharInfo[13],
      (void *)&GUI_FontHZhwhb_32_Propd1d0 
};
/*平--平*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propc6bd= {
      0xc6bd,
      0xc6bd,
      &GUI_FontHZhwhb_32_CharInfo[12],
      (void *)&GUI_FontHZhwhb_32_Propcca8 
};
/*开--开*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propbfaa= {
      0xbfaa,
      0xbfaa,
      &GUI_FontHZhwhb_32_CharInfo[11],
      (void *)&GUI_FontHZhwhb_32_Propc6bd 
};
/*究--究*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propbebf= {
      0xbebf,
      0xbebf,
      &GUI_FontHZhwhb_32_CharInfo[10],
      (void *)&GUI_FontHZhwhb_32_Propbfaa 
};
/*奋--奋*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propb7dc= {
      0xb7dc,
      0xb7dc,
      &GUI_FontHZhwhb_32_CharInfo[9],
      (void *)&GUI_FontHZhwhb_32_Propbebf 
};
/*贰--发*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propb7a1= {
      0xb7a1,
      0xb7a2,
      &GUI_FontHZhwhb_32_CharInfo[8],
      (void *)&GUI_FontHZhwhb_32_Propb7dc 
};
/*斗--斗*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propb6b7= {
      0xb6b7,
      0xb6b7,
      &GUI_FontHZhwhb_32_CharInfo[7],
      (void *)&GUI_FontHZhwhb_32_Propb7a1 
};
/*板--版*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Propb0e5= {
      0xb0e5,
      0xb0e6,
      &GUI_FontHZhwhb_32_CharInfo[5],
      (void *)&GUI_FontHZhwhb_32_Propb6b7 
};
/*S--T*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Prop0053= {
      0x0053,
      0x0054,
      &GUI_FontHZhwhb_32_CharInfo[3],
      (void *)&GUI_FontHZhwhb_32_Propb0e5 
};
/*M--M*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Prop004d= {
      0x004d,
      0x004d,
      &GUI_FontHZhwhb_32_CharInfo[2],
      (void *)&GUI_FontHZhwhb_32_Prop0053 
};
/*2--3*/
GUI_FLASH  const GUI_FONT_PROP GUI_FontHZhwhb_32_Prop0032= {
      0x0032,
      0x0033,
      &GUI_FontHZhwhb_32_CharInfo[0],
      (void *)&GUI_FontHZhwhb_32_Prop004d 
};
GUI_FLASH const GUI_FONT GUI_FontHZ_hwhb_32 = {
      GUI_FONTTYPE_PROP_SJIS, 
      32, 
      32, 
      1,  
      1,  
      (void GUI_FLASH *)&GUI_FontHZhwhb_32_Prop0032
};
